version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    target-branch: "develop"
    pull-request-branch-name:
      separator: "-"
    schedule:
      interval: "cron"
      cron: "50 14 * * *"
